### PR TITLE
chore: format all docs

### PR DESCRIPTION
**Pull request by ryan4yin**
Related to #31 

`markdown-it-cjk-breaks` will not work if any line starts with `[xxx]()`, e.g.:

```
Nix 语言自身提供了一些精简的内建函数，可通过 `builtins.xxx` 这种方式使用，官方文
档参见
[Built-in Functions - Nix Manual](https://nix.dev/manual/nix/2.22/language/builtins#built-in-functions).
```

Error log:

```bash
› pnpm docs:dev

> nix-press@1.0.2 docs:dev /Users/ryan/codes/src/nixos-cn.github.io
> vuepress dev src

✖ Initializing and preparing data - failed in 66ms
TypeError: Expected a code point, got `undefined`.
    at validate (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/get-east-asian-width@1.2.0/node_modules/get-east-asian-width/index.js:5:9)
    at eastAsianWidthType (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/get-east-asian-width@1.2.0/node_modules/get-east-asian-width/index.js:10:2)
    at process_inlines (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/markdown-it-cjk-breaks@2.0.0/node_modules/markdown-it-cjk-breaks/index.mjs:49:24)
    at Array.cjk_breaks (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/markdown-it-cjk-breaks@2.0.0/node_modules/markdown-it-cjk-breaks/index.mjs:65:5)
    at Core.process (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/parser_core.mjs:56:13)
    at MarkdownIt.parse (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/index.mjs:511:13)
    at MarkdownIt.render (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/markdown-it@14.1.0/node_modules/markdown-it/lib/index.mjs:530:36)
    at md.render (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/@mdit-vue+plugin-frontmatter@2.0.0/node_modules/@mdit-vue/plugin-frontmatter/dist/index.mjs:22:12)
    at md.render (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/@mdit-vue+plugin-sfc@2.0.0/node_modules/@mdit-vue/plugin-sfc/dist/index.mjs:30:22)
    at c.render (file:///Users/ryan/codes/src/nixos-cn.github.io/node_modules/.pnpm/vuepress-plugin-md-enhance@2.0.0-rc.31_flowchart.ts@3.0.0_katex@0.16.9_markdown-it@14.1.0_mer_j62dcldj4tz3xflzj3hzxcawuy/node_modules/vuepress-plugin-md-enhance/lib/node/index.js:97:2233)
 ELIFECYCLE  Command failed with exit code 1.
```

### CODE REVIEW

**Comment by TatooiNoyo** [comment]
It seems to have been resolved in this [PR](https://github.com/markdown-it/markdown-it-cjk-breaks/pull/5), but not merged yet.

**Comment by TatooiNoyo** [comment]
look
https://github.com/searKing/preview-vscode/issues/87#issuecomment-2109323938

**Comment by TatooiNoyo** [comment]
This pr should be reverted. 
See [two comments](https://github.com/NixOS-CN/nixos-cn.github.io/pull/32#discussion_r1658683286) that provide explanations and solutions.
@ryan4yin

**Comment by ryan4yin** [comment]
@TatooiNoyo Did the PR #33 you submitted resolve the problem?
Everything works fine currently, the site can render and release normally, and there is no problem with the cjk break.
I don't think this PR should be reverted.

**Comment by TatooiNoyo** [comment]
> @TatooiNoyo Did the PR #33 you submitted resolve the problem?
This PR only fixes the build failure exception.

> Everything works fine currently, the site can render and release normally, and there is no problem with the cjk break.

Please check the layout of the 
[tutor ials](https://nixos-cn.org/tutorials/installation/WSL2.html). direct formatting can cause abnormal layouts of the original design.

**Comment by ryan4yin** [comment]
> Please check the layout of the
> [tutor ials](https://nixos-cn.org/tutorials/installation/WSL2.html). direct formatting can cause abnormal layouts of the original design.

Sorry haven't notice that before, reverted.

**Comment by TatooiNoyo** [comment]
> Sorry haven't notice that before, reverted.
@ryan4yin 
If you don't mind, I would be happy to provide an PR to format all the documents.

**Comment by ryan4yin** [comment]
@TatooiNoyo PRs are welcome~

**Pull request merged**
